<?php

namespace AppBundle\Repository;

/**
 * Tour_BackgroundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourBackgroundRepository extends \Doctrine\ORM\EntityRepository
{
}
