<?php

namespace AppBundle\Repository;

/**
 * TourRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
