<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tour;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * TourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findOpenTours()
    {
        return $this->findBy(array('status' => Tour::STATUS_OPEN));
    }

    /**
     * @return static
     */
    public function queryOpenTours()
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT t
                FROM AppBundle:Tour t
                WHERE t.status = :status
            ')
            ->setParameter('status', Tour::STATUS_OPEN);
    }

    /**
     * @param int $page
     * @return Pagerfanta
     */
    public function findLastest($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryOpenTours(), false));
        $paginator->setMaxPerPage(2);
        $paginator->setCurrentPage($page);

        return $paginator;
    }
}
