<?php

namespace AppBundle\Repository;

/**
 * TourTransportationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourTransportationRepository extends \Doctrine\ORM\EntityRepository
{
}
