<?php

namespace AppBundle\Repository;

/**
 * TourServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
