<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tour;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * TourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findOpenTours()
    {
        return $this->findBy(array('status' => Tour::STATUS_OPEN), null, 8);
    }

    /**
     * @return static
     */
    public function queryOpenTours()
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT t
                FROM AppBundle:Tour t
                WHERE t.status = :status
            ')
            ->setParameter('status', Tour::STATUS_OPEN);
    }

    /**
     * @param int $page
     * @return Pagerfanta
     */
    public function findLastest($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryOpenTours(), false));
        $paginator->setMaxPerPage(5);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

    /**
     * @param Tour $tour
     * @return int
     */
    public function getRemainSeats(Tour $tour)
    {
        $orders = $tour->getTourOrders();

        $remain = $tour->getNumberOfPeople();

        foreach ($orders as $order) {
            if ('canceled' !== $order->getStatus()) {
                $people = $order->getNumberOfPeople();

                $remain -= $people;

                if ($remain < 0) {
                    $remain = 0;
                    break;
                }
            }
        }

        return $remain;
    }
}
