<?php

namespace AppBundle\Repository;

/**
 * TourCancelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourCancelRepository extends \Doctrine\ORM\EntityRepository
{
}
