<?php

namespace AppBundle\Repository;

/**
 * TourOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
