<?php

namespace AppBundle\Repository;

/**
 * TourInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourInvoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
