<?php

namespace AppBundle\Repository;

/**
 * TourHotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourHotelRepository extends \Doctrine\ORM\EntityRepository
{
}
