<?php

namespace AppBundle\Repository;

/**
 * TourCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
