<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tour;
use Doctrine\ORM\EntityRepository;

/**
 * TourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends EntityRepository
{
    public function findOpenTours()
    {
        return $this->findBy(array('status' => Tour::STATUS_OPEN));
    }
}
