<?php

namespace AppBundle\Repository;

/**
 * TourLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
