<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TourOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourOrderRepository extends EntityRepository
{
    public function getUserOrders($findBy = array())
    {
        return $this->findBy($findBy);
    }
}
