<?php

namespace AppBundle\Repository;

/**
 * TransportationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportationRepository extends \Doctrine\ORM\EntityRepository
{
}
