# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.user_manager:
            class: AppBundle\Manager\UserManager
            arguments:
                - "@service_container"
                - "@doctrine.orm.entity_manager"
                - AppBundle\Entity\User

    app.tour_manager:
        class: AppBundle\Manager\TourManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - AppBundle\Entity\Tour

    app.tour_order_manager:
        class: AppBundle\Manager\TourOrderManager
        arguments:
            - "@security.token_storage"
            - "@doctrine.orm.entity_manager"
            - AppBundle\Entity\TourOrder

    app.comment_manager:
            class: AppBundle\Manager\CommentManager
            arguments:
                - "@doctrine.orm.entity_manager"
                - AppBundle\Entity\Comment

    app.slugger:
        class: AppBundle\Utils\Slugger

    app.block.recent_user_comment:
        class: AppBundle\Block\RecentUserCommentBlockService
        arguments:
            - app.block.recent_user_comment
            - "@templating"
            - "@app.comment_manager"
            - "@app.user_manager"
        tags:
            - { name: sonata.block }

    app.block.user_orders:
          class: AppBundle\Block\UserOrderBlockService
          arguments:
              - app.block.recent_user_comment
              - "@templating"
              - "@app.tour_order_manager"
          tags:
              - { name: sonata.block }

    app.form.type.tour_order:
        class: AppBundle\Form\TourOrderType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    app.form.type.tour_request:
        class: AppBundle\Form\TourRequestType
        arguments: ["@app.tour_order_manager"]
        tags:
            - { name: form.type }

    app.menu_listener:
        class: AppBundle\EventListener\MenuBuilderListener
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    app.template.travel_template:
        class: AppBundle\Pager\TravelTemplate

    pager.fanta.travel_template:
        class: Pagerfanta\View\DefaultView
        public: false
        arguments:
            - "@app.template.travel_template"
        tags: [{ name: pagerfanta.view, alias: travel_template }]