services:
    app.admin.tour:
        class: AppBundle\Admin\TourAdmin
        arguments: [~, AppBundle\Entity\Tour, AppBundle:TourAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Tour }

    app.admin.location:
        class: AppBundle\Admin\LocationAdmin
        arguments: [~, AppBundle\Entity\Location, AppBundle:LocationAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Location }

    app.admin.tour_location:
        class: AppBundle\Admin\TourLocationAdmin
        arguments: [~, AppBundle\Entity\TourLocation, AppBundle:TourLocationAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: TourLocation }

    app.admin.hotel:
        class: AppBundle\Admin\HotelAdmin
        arguments: [~, AppBundle\Entity\Hotel, AppBundle:HotelAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Hotel }

    app.admin.tour_hotel:
        class: AppBundle\Admin\TourHotelAdmin
        arguments: [~, AppBundle\Entity\TourHotel, AppBundle:TourHotelAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: TourHotel }

    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, AppBundle:UserAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }

    app.admin.tour_category:
        class: AppBundle\Admin\TourCategoryAdmin
        arguments: [~, AppBundle\Entity\TourCategory, AppBundle:TourCategoryAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: TourCategory }

    app.admin.tour_background:
        class: AppBundle\Admin\TourBackgroundAdmin
        arguments: [~, AppBundle\Entity\TourBackground, AppBundle:TourBackgroundAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: TourBackground }
